import mongoose from "mongoose";

const alertSchema = new mongoose.Schema(
  {
    title: { type: String, required: true },
    message: { type: String, required: true },
    type: { type: String, enum: ["info", "success", "warning", "urgent", "cohort"], default: "info" },
    link: { type: String, default: "" },
    startAt: { type: Date },
    endAt: { type: Date },
    isActive: { type: Boolean, default: true, index: true },
    pinned: { type: Boolean, default: false },
    cohort: { type: mongoose.Schema.Types.ObjectId, ref: "Cohort" },
    autoGenerated: { type: Boolean, default: false },
    createdBy: { type: mongoose.Schema.Types.ObjectId, ref: "User" }
  },
  { timestamps: true }
);

export const Alert = mongoose.model("Alert", alertSchema);
