import { Alert } from "../models/Alert.js";
import { Application } from "../models/Application.js";
import { AuditLog } from "../models/AuditLog.js";
import { Certificate } from "../models/Certificate.js";
import { Cohort } from "../models/Cohort.js";
import { ContactMessage } from "../models/ContactMessage.js";
import { Post } from "../models/Post.js";
import { Testimonial } from "../models/Testimonial.js";
import { Trade } from "../models/Trade.js";
import { User } from "../models/User.js";
import { ApiError } from "../utils/ApiError.js";
import { asyncHandler } from "../utils/asyncHandler.js";

function addMonths(date, months) {
  const next = new Date(date);
  const day = next.getDate();
  next.setMonth(next.getMonth() + months);
  if (next.getDate() < day) next.setDate(0);
  return next;
}

async function audit(req, action, entity, entityId, meta = {}) {
  await AuditLog.create({ actor: req.user._id, action, entity, entityId: String(entityId || ""), meta });
}

export const overview = asyncHandler(async (_req, res) => {
  const [applications, cohorts, messages, certificates, trades, students] = await Promise.all([
    Application.countDocuments(),
    Cohort.countDocuments(),
    ContactMessage.countDocuments({ status: "new" }),
    Certificate.countDocuments(),
    Trade.countDocuments(),
    User.countDocuments({ role: "student" })
  ]);
  const byStatus = await Application.aggregate([{ $group: { _id: "$status", count: { $sum: 1 } } }]);
  res.json({
    applications,
    cohorts,
    messages,
    certificates,
    trades,
    students,
    applicationStatus: Object.fromEntries(byStatus.map((row) => [row._id, row.count]))
  });
});

export const listApplications = asyncHandler(async (req, res) => {
  const filter = {};
  if (req.query.status) filter.status = req.query.status;
  const items = await Application.find(filter).sort({ createdAt: -1 }).limit(100).lean();
  res.json({ items });
});

export const updateApplicationStatus = asyncHandler(async (req, res) => {
  const application = await Application.findById(req.params.id);
  if (!application) throw new ApiError(404, "Application not found.");
  application.status = req.body.status;
  application.reviewedBy = req.user._id;
  if (req.body.status === "approved") {
    const student = await User.findOne({ email: application.email });
    if (student) application.user = student._id;
  }
  await application.save();
  await audit(req, "application.status", "Application", application._id, { status: application.status });
  res.json({ item: application });
});

export const listCohorts = asyncHandler(async (_req, res) => {
  const items = await Cohort.find().sort({ startDate: 1 }).lean();
  res.json({ items });
});

export const createCohort = asyncHandler(async (req, res) => {
  const startDate = new Date(req.body.startDate);
  if (Number.isNaN(startDate.getTime())) throw new ApiError(400, "Enter a valid start date.");
  const cohort = await Cohort.create({
    name: req.body.name,
    startDate,
    endDate: addMonths(startDate, 3),
    mode: req.body.mode,
    seatLimit: req.body.seatLimit || 20,
    priceFrom: req.body.priceFrom ?? 120,
    sessionLinks: { zoom: req.body.zoom || "", meet: req.body.meet || "" },
    venue: req.body.venue || "",
    notes: req.body.notes || "",
    status: "draft",
    createdBy: req.user._id
  });
  if (req.body.publishAlert) {
    const alert = await Alert.create({
      title: `${cohort.name} is now listed`,
      message: `${cohort.name} starts ${startDate.toLocaleDateString("en-GB")}. ${cohort.seatLimit} seats. Plans from ${cohort.priceFrom} USD.`,
      type: "cohort",
      link: "/programme",
      isActive: true,
      cohort: cohort._id,
      autoGenerated: true,
      createdBy: req.user._id
    });
    cohort.alertId = alert._id;
    await cohort.save();
  }
  await audit(req, "cohort.create", "Cohort", cohort._id, { name: cohort.name });
  res.status(201).json({ item: cohort });
});

async function listModel(Model) {
  return asyncHandler(async (_req, res) => {
    const items = await Model.find().sort({ createdAt: -1 }).limit(100).lean();
    res.json({ items });
  });
}

export const listMessages = listModel(ContactMessage);
export const listCertificates = listModel(Certificate);
export const listTrades = listModel(Trade);
export const listAlerts = listModel(Alert);
export const listPosts = listModel(Post);
export const listTestimonials = listModel(Testimonial);

export const listStudents = asyncHandler(async (_req, res) => {
  const items = await User.find({ role: "student" }).sort({ createdAt: -1 }).limit(100);
  res.json({ items: items.map((user) => user.toPublic()) });
});
